### ISSUE TITLE
Missing support of ix:continuation

### ISSUE THREAD

**Issue by Nachtinho** [Workiva/ixbrl-viewer#107]
HI,

The ix:continuation element is used to define data that is to be treated as part of ix:footnote or ix:nonNumeric elements. The purpose of the ix:continuation element is to define text content which is to be added to the {continuous content} property of ix:footnote or ix:nonNumeric elements. It has no other use.

Unfortunately, these are not displayed correctly in the preview.

Kind regards,
Guido

**Comment by paulwarren-wk** [comment]
The viewer does have support for `ix:continuation` elements.  Can you provide an example of a document that demonstrates the problem that you are seeing?

**Comment by Nachtinho** [comment]
Hi,

I was able to recreate the issue:
[continuation issue.zip](https://github.com/Workiva/ixbrl-viewer/files/5439100/continuation.issue.zip)

The first two parts are highlighted correctly but the last one (id=klaus) not.

**Comment by paulwarren-wk** [comment]
I can recreate the issue with the provided `ixbrlviewer.js` but not with current versions of the viewer.  

I believe it was fixed in https://github.com/Workiva/ixbrl-viewer/commit/def4a0f9d26ec77a1710434615b24e501a1be03a.

**Comment by Nachtinho** [comment]
Yes, this was fixed. 

But the issue still occurs for mappings over pages.

See 
[Mapping across pages .zip](https://github.com/Workiva/ixbrl-viewer/files/6419454/Mapping.across.pages.zip)
concept: Organization, Consolidation and Presentation of Financial Statements Disclosure
starts at end of the first page and continues on the second page.

Kind regards,
Guido
