### ISSUE TITLE
 Alignment in iXBRL preview incorrect

### ISSUE THREAD

**Issue by Nachtinho** [Workiva/ixbrl-viewer#109]
After using the preview, the alignment of some ToC text has changed.

Have a look at this example: 
[example.zip](https://github.com/Workiva/ixbrl-viewer/files/4701961/example.zip)

Regards,

**Comment by paulwarren-wk** [comment]
Before:

![image](https://user-images.githubusercontent.com/45077928/84139276-7cb72a00-aa47-11ea-9009-c427a32aad73.png)

After:

![image](https://user-images.githubusercontent.com/45077928/84139322-8e003680-aa47-11ea-8569-58fccad71dda.png)

**Comment by paulwarren-wk** [comment]
The filing in the provided ZIP file is not the same as the one from the SEC, and is not valid XML.

**Comment by paulwarren-wk** [comment]
I've confirmed that this does not happen with the version downloaded directly from the SEC.
