### ISSUE TITLE
Issue with "make prod"

### ISSUE THREAD

**Issue by xbrles** [Workiva/ixbrl-viewer#12]
Dear all,

We have a problem at the moment we run "make prod", the process never finishes and there are no messages. 

We're using Windows 10 and the last version available of npm (6.9.0).

Executing "npm run test" bring some errors:

![image](https://user-images.githubusercontent.com/19322084/55820025-caae6600-5b02-11e9-8d3a-63707e445c31.png)

![image](https://user-images.githubusercontent.com/19322084/55820095-f7fb1400-5b02-11e9-89ec-7a8b6dbb6487.png)

Also attached the LOG of the execution of the "npm run test".

[2019-04-09T17_03_06_247Z-debug.log](https://github.com/Workiva/ixbrl-viewer/files/3060169/2019-04-09T17_03_06_247Z-debug.log)

Any support is very much appreciated.

Thanks in advance for your help!

--------------
Javier Mora
XBRL Spain
info@xbrl.es
--------------

**Comment by paulwarren-wk** [comment]
bc3aa0a9835395d40ba15b03151e43da23320d0a should hopefully fix the issue with the tests.  

I'm not sure what the issue is with make prod.  Does "make dev" work any better?

**Comment by xbrles** [comment]
Hi Paul,

Thanks for your help! Let me explain you step by step what I'm doing.

**STEP 1.** After installing npm, I've run "npm install" with this result:

![image](https://user-images.githubusercontent.com/19322084/56461648-90707e80-63b6-11e9-97d6-e780b28943f7.png)

Please, let me know if I need to fix something related to the warnings.

**STEP 2.** After your last commit, I've successfully run the javascript unit tests with "npm run test"

![image](https://user-images.githubusercontent.com/19322084/56461663-e3e2cc80-63b6-11e9-941e-21f21624fd32.png)

**STEP 3.** Both commands: "make prod" and "make dev" have the same result, the blinking underscore symbol as the process never finishes and no error messages related.

![image](https://user-images.githubusercontent.com/19322084/56461668-f8bf6000-63b6-11e9-870e-40c52927fafe.png)

Any ideas of how can I solve this issue?

Thanks in advance for your help!

-----------------------
Javier Mora
XBRL Spain
info@xbrl.es
-----------------------

**Comment by paulwarren-wk** [comment]
Can you try doing:

```
cd iXBRLViewerPlugin\viewer
npx webpack --config webpack.dev.js --optimize-minimize
```

**Comment by xbrles** [comment]
Hi Paul,

This is the result of running these commands.

![image](https://user-images.githubusercontent.com/19322084/56467553-c4808980-6420-11e9-93d7-a6742dc40e58.png)

It looks like the process finishes successfully and the "ixbrlviewer.js" file has been created in the "iXBRLViewerPlugin/viewer/dist" directory.

![image](https://user-images.githubusercontent.com/19322084/56467638-cd258f80-6421-11e9-8d28-7cc686b1fd46.png)

Thanks for your help!

---------------
Javier Mora
XBRL Spain
info@xbrl.es
---------------

**Comment by paulwarren-wk** [comment]
Glad it's working.  The two files are interchangeable - the .dev version just contains extra information for debugging.  If you want the normal version, just use:

```
npx webpack --config webpack.prod.js --optimize-minimize
```

**Comment by paulwarren-wk** [comment]
There's a fix for this issue here:

https://github.com/paulwarren-wk/ixbrl-viewer/blob/issue-12-build-fixes/README.md

If you've not already got the Arelle plugin working, note the updated instructions in the above.

**Comment by xbrles** [comment]
Thank you, Paul.

The command:

`npx webpack --config webpack.prod.js --optimize-minimize`

seems to work OK, even I get some warnings

![image](https://user-images.githubusercontent.com/19322084/56470214-0e2e9b80-6444-11e9-989e-c9124d64451e.png)

Now I've both JavaScript files ("ixbrlviewer.js" and "ixbrlviewer.dev.js") on the "iXBRLViewerPlugin/viewer/dist" directory.

![image](https://user-images.githubusercontent.com/19322084/56470225-4504b180-6444-11e9-8e7b-fcc59cffe7d1.png)

**Comment by xbrles** [comment]
Paul,

I confirm that I have been able to install successfully the **iXBRL viewer plugin** on Arelle:

![image](https://user-images.githubusercontent.com/19322084/56470909-2b676800-644c-11e9-9e40-35d54799fef1.png)

Thanks for your support!

--------------
Javier Mora
XBRL Spain
info@xbrl.es
--------------

**Comment by xbrles** [comment]
Paul, 

Everything is working but the process of loading the iXBRL instance document, after saving it with the Arelle iXBRL Viewer plugin, it gets stuck on this screen:

![image](https://user-images.githubusercontent.com/19322084/56473144-367bc180-6467-11e9-8b73-ce3c32d0bc73.png)

Please, find attached the original iXBRL (Alexandria-2018-Statements.html) and the one saved by the Arelle iXBRL Viewer plugin (Alexandria-2018-Statements-ixbrlviewer.html).

[Alexandria-2018-Statements.zip](https://github.com/Workiva/ixbrl-viewer/files/3101414/Alexandria-2018-Statements.zip)

Thanks for your support!

--------------
Javier Mora
XBRL Spain
info@xbrl.es
--------------

**Comment by paulwarren-wk** [comment]
I think your -ixbrlviewer.html file was generated by an older version of the Arelle plugin than your ixbrlviewer.js file is expecting.  Could you try regenerating the file, and seeing if that fixes it?  If not, please can you report what's on the Javascript console, and attach a copy of ixbrlviewer.js?

**Comment by xbrles** [comment]
Thank you, Paul.

Indeed you're right, I was using the v0.1 (2019-**03-22**) of the Arelle iXBRL Viewer plugin.

![image](https://user-images.githubusercontent.com/19322084/56534009-1a584d00-6559-11e9-8f42-41b62461c407.png)

Now I'm using the v0.1 (2019-**04-20**) of the Arelle iXBRL Viewer plugin.

![image](https://user-images.githubusercontent.com/19322084/56534149-5db2bb80-6559-11e9-8377-c38002a0c6c6.png)

and everything works perfectly!

Thank you so much for your support!

--------------
Javier Mora
XBRL Spain
info@xbrl.es
--------------
