### ISSUE TITLE
AtrributeError: 'NoneType' object has not attribute 'type'

### ISSUE THREAD

**Issue by sonalichauhan2691** [Workiva/ixbrl-viewer#150]
I am getting [xmlSchema:syntax] Start tag expected, '<' not found, ixbrlviewer.js, line 1, column1 while loading ixblrviewer.js  in Arelle.

also getting this error while loading iXBLR instance from Tools not able to generate html file.

![ArelleError](https://user-images.githubusercontent.com/73830784/97868596-fe309100-1d35-11eb-9d68-1b760f3a529e.PNG)

Please help me to fix this issue.

**Comment by paulwarren-wk** [comment]
> I am getting [xmlSchema:syntax] Start tag expected, '<' not found, ixbrlviewer.js, line 1, column1 while loading ixblrviewer.js in Arelle.

This sounds like you're trying to open the JS file directly in Arelle.  This won't work, as Arelle can only open XBRL / iXBRL files.

> also getting this error while loading iXBLR instance from Tools not able to generate html file.

Please provide the document that you have loaded in Arelle that produces this.

**Comment by paulwarren-wk** [comment]
Closing this issue as we don't have the document to reproduce it.
