### ISSUE TITLE
Cannot expand text [..] link

### ISSUE THREAD

**Issue by freemaceo** [Workiva/ixbrl-viewer#197]
Hi,

We are encountering the following error when trying to click on [..] to expand and show all the text on Fact Value on Fact Properties: 
Uncaught TypeError: e.readableValue is not a function
    at Z._updateValue (ixbrlviewer.js:formatted:85705)

We think this issue is related to an error in: https://github.com/Workiva/ixbrl-viewer/blob/2771e79de869a40df58fc6a59dbad23b2c41b0a5/iXBRLViewerPlugin/viewer/src/js/inspector.js#L491

Can someone help us solving this issue ?

Best regards
Mahdi

**Comment by huizarmx** [comment]
Yes, that was the issue, the line should read 

`$('tr.value .show-all', context).off('click').on('click', () => { 
                this._updateValue(item, true, context) 
            });`

**Comment by freemaceo** [comment]
Many thanks @huizarmx!
Is this Bug fix in next Release ?
