### ISSUE TITLE
RFI: Processing xhtml file embedded in taxonomy package

### ISSUE THREAD

**Issue by royteeuwen** [Workiva/ixbrl-viewer#253]
Is it possible to process an xhtml file that is in the taxonomy zip package? At this moment the flow is:

unzip package.zip
python arelleCmdLine --package package.zip -f unzipped-package/reports/report.xhtml

It would be one step easier if we don't have to unzip the package

**Comment by paulwarren-wk** [comment]
This should just work:

```
$ arelle -f ~/Downloads/213800KW6MZUK12CQ815-2020-12-31.zip --plugins `pwd`/iXBRLViewerPlugin/__init__.py --save-viewer /tmp/out.html
[info] Activation of plug-in ixbrl-viewer successful, version 0.1. - /home/pdw/c.b.c/clients/workiva/ixbrl-viewer/iXBRLViewerPlugin/__init__.py 
[info] loaded in 14.22 secs at 2021-09-22T21:10:18 - /home/pdw/Downloads/213800KW6MZUK12CQ815-2020-12-31.zip/213800KW6MZUK12CQ815-2020-12-31/reports/213800KW6MZUK12CQ815-2020-12-31-T01.html 
[viewer:info] Creating iXBRL viewer - 213800KW6MZUK12CQ815-2020-12-31-T01.html 
[viewer:info] Writing /tmp/out.html - 213800KW6MZUK12CQ815-2020-12-31-T01.html 
```

**Comment by royteeuwen** [comment]
Hey @paulwarren-wk 
Cool, that works!

Second question while we are at it, I don't see an easy way to develop the ixbrl-viewer.js, or am I missing something? There is no live reload on a mock html file or something, right? I would like to update some styling on how the end result looks like but it's not easy to update

**Comment by paulwarren-wk** [comment]
No, there's no easier way to develop ixbrl-viewer.js, but if you use a small, test HTML file, loading the viewer is very quick, so it's only a matter of a few seconds to rebuild ixbrl-viewer.js, and reload the file.
