### ISSUE TITLE
Error on load caused by unrecognized script tag

### ISSUE THREAD

**Issue by ChristopheDeBernardi** [Workiva/ixbrl-viewer#282]
**Important:**

I'm using the 1.0.3 release because it seems that newer versions do not work well with ESEF reports (but that's another issue).  
I don't think the version difference is related with my current problem but it's worth mentioning.

---

#### Description

In certain conditions opening the viewer gives a `Could not find viewer data` error.  
Unfortunately I was not able to determine the root cause of the issue nor can I provide the relevant iXBRL instance, because it is an actual financial report which may not be public yet.

![image](https://user-images.githubusercontent.com/57985290/153189813-272f1d96-eb95-4fc4-a157-62db1dcd9be3.png)

However I found out that the data is not detected because the <script> tag enclosing the JSON data is actually prefixed with the xhtml namespace:

![image](https://user-images.githubusercontent.com/57985290/153190658-ee0bf485-d0f3-4d34-862d-c29857b629de.png)

I thought this was because this prefix is explicitly defined in the report...

![image](https://user-images.githubusercontent.com/57985290/153190876-b1d8ace4-ef90-4fb2-8510-bef6d3053b54.png)

... but I was not able to reproduce the problem that way.

(_Edit_: I tried creating a viewer after removing that xhtml namespace prefix declaration from the original report and it worked, so I guess that is the problem after all.  
Still this case could be addressed.)

I suppose the problem could be fixed either when the viewer is created in Arelle...

![image](https://user-images.githubusercontent.com/57985290/153192728-17e2b84b-e7ad-4c92-be1b-f76396b9bb35.png)

... or in the javascript during the lookup for the `<script type="application/x.ixbrl-viewer+json">` (maybe by looking at the `localName` rather than the `tagName`?):

![image](https://user-images.githubusercontent.com/57985290/153194778-238c26ea-8ca6-4c27-95a0-a5909c5a1e41.png)

![image](https://user-images.githubusercontent.com/57985290/153195164-d6f60869-5114-4442-a3d9-75fce1e04cd8.png)

---

#### Miscellaneous

I mentionned two people in the issue for review (because the last one I wrote is still open ;) ), I hope that's ok.

**review**:
@derekgengenbacher-wf @sagesmith-wf

**Comment by paulwarren-wk** [comment]
What browser are you using, and how are you accessing the file?  Is it behind a web server, and what file extension does it have?  The fact that this is happening makes me think that it's being treated as HTML rather than XHTML.

We should still try to fix it, as we try to make the viewer work in both HTML and XHTML modes.

**Comment by ChristopheDeBernardi** [comment]
* I reproduced the issue with Firefox and Chrome
* The original problem occurred while serving the XHTML file from a web server, but I reproduced it by opening a file from my PC, with the javascript file also available locally
* The file has an `.xhtml` extension

After further tests I managed to create [this iXBRL instance](https://github.com/Workiva/ixbrl-viewer/files/8451621/ixbrl-viewer.282.zip) that triggers this issue. (It's a report package derived from the ESEF conformance suite 2021)

As I suspected, the problem is caused by a namespace prefix, but the position of the declaration is important.  
For instance the following structure will cause the problem:

![image](https://user-images.githubusercontent.com/57985290/162434538-b9a6eff0-054a-4b9f-ae4b-419c95483ae2.png)

But this one where the order of lines is different will not:

![image](https://user-images.githubusercontent.com/57985290/162434907-31f3c48d-f32d-45ea-8852-442a98004748.png)

**Comment by paulwarren-wk** [comment]
I've confirmed that the order of the namespace declarations does seem to be important here.  It appears that lxml uses the first prefix it finds for a given namespace when choosing which prefix to use for newly created elements, and there does not appear to be anyway to override this.

Switching to `localName` rather than `tagName` will fix this particular problem, but there's a related problem which is that if the `<script>` tag which references the viewer JS gets included as `<xhtml:script>` the viewer won't load at all of if the document gets loaded in HTML mode.

**Comment by paulwarren-wk** [comment]
I think I have found a way.  If we use `SubElement()` rather than `Element()` then `append()`, it seems to respect our namespace prefix preferences:

```python
from lxml import etree

xml='''
<a:foo 
xmlns:a="https://www.example.com"
xmlns="https://www.example.com" 
>
</a:foo>
'''

x = etree.fromstring(xml)

e = etree.Element("{https://www.example.com}script", nsmap = { None: 'https://www.example.com' })
x.append(e)
print("Create then append: " + str(e.prefix))

e = etree.SubElement(x, '{https://www.example.com}script', nsmap = { None: 'https://www.example.com' })
print("Sub element: " + str(e.prefix))

print(etree.tostring(x, method="xml", xml_declaration=True, pretty_print=True).decode())
```

Produces:

```
Create then append: a
Sub element: None
<?xml version='1.0' encoding='ASCII'?>
<a:foo xmlns:a="https://www.example.com" xmlns="https://www.example.com">
<a:script/><script/></a:foo>
```
