### ISSUE TITLE
Move to next and Move to previous don't work

### ISSUE THREAD

**Issue by Nachtinho** [Workiva/ixbrl-viewer#319]
Hi,

the text is partly double tagged.

When I use the previous or next button, it doesn't show the second tagging.

[Bug.example.zip](https://github.com/Workiva/ixbrl-viewer/files/9416693/Bug.example.zip)

Kind regards,

**Comment by austinmatherne-wk** [comment]
Hi @Nachtinho. Your test doc appears to have been fixed by #225.

If you're still having issues with the latest release of ixbrl-viewer we can reopen this issue.
