### ISSUE TITLE
Highlight issue in some reports where pages are tagged.

### ISSUE THREAD

**Issue by alexdejong1723** [Workiva/ixbrl-viewer#340]
Some reports do not highlight all blocktagged facts, like the 2021 polilight report, where this entire text should be highlighted:
![image](https://user-images.githubusercontent.com/46780201/201952235-33b96aba-764e-48d6-a961-d0974e777f6c.png)

The highlighted text are facts inside a textblock. It is possible to click on this fact, even though it is not highligted.

The report can be downloaded here: [https://www.polight.com/investors/reports-and-presentations/default.aspx](https://www.polight.com/investors/reports-and-presentations/default.aspx)

I believe this can be fixed by changing the css of some of the classes like `ixbrl-highlight` and `ixbrl-highlight-1` etc. by adding a * behind the classname, like `ixbrl-highlight * {...}`. This should add the background color to all child elements of the tagged.
Make sure this is added to all highlighting classes, otherwise the ones without the * will be overridden by the ones with a *.

**Comment by paulwarren-wk** [comment]
Thanks for reporting this.  I can't reproduce it using the report published on the company's website, as I can't find a text block tag, other than the ones highlighted above.  Is the text block definitely present in their published report?  If so, what's the tag name?

Also, which version of the viewer are you using?  This document looks like text block tags would trigger the bug that was fixed in https://github.com/Workiva/ixbrl-viewer/pull/325

**Comment by alexdejong1723** [comment]
[2138007ZPDNUIHX6Z659-2021-12-31-en.zip](https://github.com/Workiva/ixbrl-viewer/files/10022598/2138007ZPDNUIHX6Z659-2021-12-31-en.zip)
I'm sorry, I got this file interally and I assumed it was the same as on the website, but this one is a testfile where blocktags have been added. 

Where can I see the version of the viewer? I downloaded the latest files and added them to Arelle, but it keeps saying it's version 0.1.

**Comment by paulwarren-wk** [comment]
No problem.  This is what I get with the latest version of the viewer from git:

![image](https://user-images.githubusercontent.com/45077928/202209225-c0b2a429-f715-4256-bb0c-8fda00a04dee.png)

I'm not actually sure how to tell what version of the viewer you have.  Where exactly did you download it from?

The fact that you can't easily see the nested facts in the above example is a known issue (https://github.com/Workiva/ixbrl-viewer/issues/326#issuecomment-1262097834)

**Comment by alexdejong1723** [comment]
Then this issue does not exist. I'll try and figure out how to update properly. I downloaded the files from here by cloning.
