### ISSUE TITLE
[REQUEST] Add a version export button

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/ixbrl-viewer#368]
### What should we change and why?

The ixbrl-vewer bug reporting template asks for a version of the ixbrl-viewer to be included for easier debugging. Currently, to get the version of the ixbrl-viewer being used, a user would have to inspect the html document to find the script import which requires some technical abilities. Another issue with this is if the user is building their ixbrl-viewer using a locally built viewer then there is no discernible version included (`ixbrlviewer.js`). We should add a version export button that allows users to easily export the version of the ixbrl-viewer script that is being used and/or the githash used to build the viewer similar to how arelle does

**Comment by austinmatherne-wk** [comment]
Does this need a button, or could we just display the version in a corner?

**Comment by sagesmith-wf** [comment]
> could we just display the version in a corner

I think that is a wonderful idea
