### ISSUE TITLE
[REQUEST] ixbrl-viewer plugins cannot be loaded through the gui on startup without duplicating the python code

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/ixbrl-viewer#373]
### What should we change and why?

It is unclear to me what needs to happen here, but when you create a plugin to the ixbrl-viewer, it isn't actually possible to load it for the arelle gui without duplicating the entire python build as well. The current process for ixbrl-viewer plugins is that you are meant to override only the js (following [PLUGINS.md](https://github.com/Workiva/ixbrl-viewer/blob/master/PLUGINS.md)) so when you load arelle by pointing to the ixbrl-viewer it uses whatever was packaged with that python build. Then if you save you are allowed to point at your plugin.

**Comment by austinmatherne-wk** [comment]
Will be handled in #520
