### ISSUE TITLE
[BUG] Windows build failure - VIEWER_VERSION is not recognized

### ISSUE THREAD

**Issue by austinmatherne-wk** [Workiva/ixbrl-viewer#397]
### What happened?

The method introduced in #392 to define the viewer version [doesn't work on Windows](https://github.com/Arelle/Arelle/actions/runs/4480547741/jobs/7876014985).

> \> ixbrl-viewer@0.0.0 prod
> \> VIEWER_VERSION=`git describe --tags --dirty` webpack --config iXBRLViewerPlugin/viewer/webpack.prod.js
>
> 'VIEWER_VERSION' is not recognized as an internal or external command,
> operable program or batch file.
> Error: Process completed with exit code 1.

### Version

1.1.55

### With which browsers are you experiencing the bug?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by sagesmith-wf** [comment]
@paulwarren-wk FYI this was blocking arelle from releasing on windows because its bundled in the windows release so we reverted it for now until we can make it work properly on all platforms
