### ISSUE TITLE
[REQUEST] Brand the ixbrl-viewer with the arelle logo instead of the workiva logo

### ISSUE THREAD

**Issue by sagesmith-wf** [Workiva/ixbrl-viewer#400]
### What should we change and why?

This product is going to fall under the arelle ecosystem in the future. The first step is to change the logo/branding before eventually moving the repo.  FYI @hefischer @Workiva/xt

**Comment by paulwarren-wk** [comment]
Is the Arelle logo available as an SVG?

I'm assuming that this should replace the current Workiva logo.  Do we want to keep the "powered by" bit?
