### ISSUE TITLE
Add review mode with untagged numbers highlighting

### ISSUE THREAD

**Issue by austinmatherne-wk** [Workiva/ixbrl-viewer#453]
### What should we change and why?

We should add the ability to highlight untagged numbers and dates similar the XBRL tag highlighting that currently exists.

**Comment by paulwarren-wk** [comment]
A couple of thoughts on this:

* As currently implemented in the Workiva plugin, this replaces the ability to highlight different namespaces in different colors.  I don't think we want to lose this functionality completely.
* Some users use the viewer to produce an interactive version of their finalized report.  They may not wish to make the untagged number/date functionality as obvious as it is currently is in the Workiva plugin.

Possible ideas:

* Implement a "review mode", which would be a checkbox item on the settings menu.
* Make this functionality a build-time option (this could be either JS-build time, or viewer document build time).
* Use a query parameter to enable review mode.

**Comment by austinmatherne-wk** [comment]
Retaining the existing namespace color highlighting is certainly a requirement.

Another consideration to think about is the potential additional time spent on preprocessing, specifically when it comes to wrapping untagged numbers so that they can be highlighted (and any other future "review" functionality we may want to add). Weighing the three options, my preference leans towards the query parameter. This option provides maximum flexibility as it allows the same viewer to be utilized both with and without the review mode. Moreover, it can minimize preprocessing overhead when the review mode is not activated.

**Comment by RamkumarAlagupandian** [comment]
@austinmatherne-wk  - **Thank you so much for adding this as feature. Much Appreciated.**  

Having the untagged number and date displayed in the inline viewer would greatly benefit to users in terms of reviewing. It is an extremely valuable feature for all users.

Currently we have a feature to print the document, it would be incredibly useful if we could provide an option to export it as a PDF with untagged values and dates with highlights.

I am eagerly anticipating the arrival of this feature and I look forward to hearing from you.
